# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.box = "ubuntu/xenial64"
   
# Setup memory for the virtual machine
config.vm.provider "virtualbox" do |v|
	v.memory = 16000
	v.cpus = 7
end

config.vm.network "forwarded_port", guest: 8000, host: 8000
config.vm.network "forwarded_port", guest: 3000, host: 3000

config.ssh.forward_agent = true

config.vm.provision "shell", path: "provision.sh"

end